### ISSUE TITLE
plop generator produces invalid commands

### ISSUE THREAD

**Issue by vroland** [serlo/editor-plugins#55]
While trying to use the plop generator for generating plugins for higher education, running `yarn generate <plugin name>` yields:
```
"format": "prettier --write &quot;{{__tests__,src}/**/*,*}.{js,jsx,ts,tsx,css,scss,sass,less,json,md,markdown,yaml,yml}&quot;"
```
in the `"scripts"` section of the `package.json` of the generated plugin. (note `&quot;` instead of `\"`) Thus, `yarn format` will fail with `invalid command`. 
As a workarround I changed `prettierCommand` to be a template partial, but this does not seem like the most idiomatic solution to me. Any ideas on this?

**Comment by Knorrke** [comment]
I'll take a look. Had the problem before, because prettier formated the string in the plop file. Got this to work back then, probably pittier messed with it again...
